Before you turn this problem in, make sure everything runs as expected. First, **restart the kernel** (in the menubar, select Kernel$\rightarrow$Restart) and then **run all cells** (in the menubar, select Cell$\rightarrow$Run All).

Make sure you fill in any place that says `YOUR CODE HERE` or "YOUR ANSWER HERE", as well as your name and collaborators below:

In [ ]:
NAME = ""
COLLABORATORS = ""

---
# Homework set 2

# Exercise 0
Write down the names + student ID of the people in your group.

YOUR ANSWER HERE

Run the following cell to import the nessecary packages.

In [10]:
import scipy.linalg as lu
import numpy as np
import matplotlib.pyplot as plt

-----
# Exercise 1 (2.1 on the Exercise sheet)

##### NOTE: You may also submit Exercise 1 as a pdf of your handwritten solutions if you prefer. If so, indicate this where you would put your answers below

## (a) 1 point
Let $A$ be the matrix $\begin{bmatrix} 1 & -1 & \alpha \\ 2 & 2 & 1 \\ 0 & \alpha & -3/2 \end{bmatrix}$. For which values of $\alpha$ is $A$ singular?

### Answer:

A matrix is singular when the Det(A) = 0

$Det(A) = 0$ 
  
$Det(A) = (2 * -\frac{3}{2} - \alpha) - (-1)(2 * -\frac{3}{2}) + \alpha(2 \alpha)$  
  
$-3-3- \alpha + 2 \alpha^2 = 0$
  
$\alpha^2 - -\frac{1}{2} \alpha - 3 = 0 $

$\alpha = 2$ OR $\alpha = -\frac{3}{2}$


## (b) 1 point
Consider the following linear system of equations:
$$
\begin{align*}
2x + y + z & = 3 \\
2x - y + 3z &= 5 \\
-2x + \alpha y + 3z &= 1.
\end{align*}
$$
For what values of $\alpha$ does this system have an infinite number of solutions?

### Answer:

As a system is singular, a system can have a infinite number of solutions. A system is singular when $det(A) = 0$.

$\alpha = -5$

## (c) 2 points
Denote the columns of an $n \times n$ matrix $A$ as $A_k$ for $k=1,\ldots,n$. We define the function $||A||_* = \max_k ||A_k||_2$. Show that $||A||_*$ is a norm, in that it satisfies the first three properties of a matrix norm (cf. §2.3.2).

YOUR ANSWER HERE

----
# Exercise 2
For solving linear systems such as $Ax = b$, it is unnecessary (and often unstable) to compute the inverse $A^{-1}$. Nonetheless, there can be situations where it is useful to compute $A^{-1}$ explicitly. One way to do so is by using the LU-decomposition of $A$.

## (a) 2 points
Write an algorithm to compute $A^{-1}$ for a non-singular matrix $A$ using its LU-decomposition. You can use `scipy.linalg.lu` (which returns an LU-decomposition with _partial pivoting_, i.e., with a permutation matrix $P$) and the other `scipy.linalg.lu_*` functions, but not `scipy.linalg.inv` (or other methods for computing matrix inverses directly).

In [14]:
def invert(A):
    
    A_inv = np.array([[1,0,0], [0,1,0], [0,0,1]])
    
    P, L, U = la.lu(A)
    print(P)
    print(L)
    print(U)
    
    return A_inv

matrix = np.array([[2,1,1], [2,-1,3], [-2, 100, 3]])
print(matrix)
invert(matrix)


[[  2   1   1]
 [  2  -1   3]
 [ -2 100   3]]
[[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]
[[ 1.          0.          0.        ]
 [-1.          1.          0.        ]
 [ 1.         -0.01980198  1.        ]]
[[  2.           1.           1.        ]
 [  0.         101.           4.        ]
 [  0.           0.           2.07920792]]


array([[  2,   1,   1],
       [  2,  -1,   3],
       [ -2, 100,   3]])

## (b) 1 point
What is the computational complexity of your algorithm, given that the input matrix has size $n \times n$?
Give a short calculation/explanation for your answer.

YOUR ANSWER HERE

## (c) 1 point
Apply your Python code to compute the inverse of the Hilbert matrix $H_n$ for $n=1, \ldots, 12$ (see https://en.wikipedia.org/wiki/Hilbert_matrix) -- you can use `scipy.linalg.hilbert`. This matrix is _very_ ill-conditioned, so computing its inverse is very hard for large $n$.

Compare the inverse with the "true" inverse given by `scipy.linalg.invhilbert`. Output a (`plt.semilogy`) graph showing how the $\infty$-norm of their difference progresses for $n$.

In [ ]:
# YOUR CODE HERE
raise NotImplementedError()

## (d) 2 points
It is known that the $2$-condition number $cond_2(H_n)$ of the Hilbert matrix grows like $\mathcal O\left(\frac{(1+\sqrt{2})^{4n}}{\sqrt{n}}\right)$. Does the $\infty$-condition number (defined in Example 2.5) of $H_n$ grow in a similar way?
For the matrix inverse, try both your own matrix inversion routine, and `scipy.linalg.invhilbert`. Output a (`plt.semilogy`) graph showing your results.

In [ ]:
# YOUR CODE HERE
raise NotImplementedError()